<option value="">اختر الحساب</option>
<option value="0">النقدية في الخزينة</option>
<option value="1"> العهد النقدية</option>
<option value="2"> حساب البنك الجاري - اسم البنك</option>
<option value="3"> المدينون</option>
<option value="4"> تأمين طبي مقدم</option>
<option value="5"> إيجار مقدم</option>
<option value="6"> مدفوعات مقدمة للموظفين</option>
<option value="7"> المخزون</option>
<option value="8"> الأراضي</option>
<option value="9"> المباني</option>
<option value="10"> المعدات</option>
<option value="11"> أجهزة مكتبية وطابعات</option>
<option value="12"> الأصول غير الملموسة</option>
<option value="13"> العقارات الاستثمارية</option>
<option value="14"> الدائنون</option>
<option value="15"> مصروفات مستحقة</option>
<option value="16"> الرواتب المستحقة</option>
<option value="17"> قروض قصيرة الأجل</option>
<option value="18"> ضريبة القيمة المضافة المستحقة</option>
<option value="19"> الضرائب المستحقة</option>
<option value="20"> إيرادات غير مكتسبة</option>
<option value="21"> مستحقات المؤسسة العامة للتأمينات الاجتماعية</option>
<option value="22"> مجمع استهلاك المباني</option>
<option value="23"> مجمع استهلاك المعدات</option>
<option value="24"> مجمع استهلاك أجهزة مكتبية وطابعات</option>
<option value="25"> مخصص مكافأة نهاية الخدمة</option>
<option value="26"> قروض طويلة أجل</option>
<option value="27"> رأس المال المسجل</option>
<option value="28"> رأس المال الإضافي المدفوع</option>
<option value="29"> أرصدة افتتاحية</option>
<option value="30"> احتياطي نظامي</option>
<option value="31"> احتياطي ترجمة عملات أجنبية</option>
<option value="32"> الأرباح والخسائر العاملة</option>
<option value="33"> الأرباح المبقاة (أو الخسائر)</option>
<option value="34"> إيرادات المبيعات/ الخدمات</option>
<option value="35"> تكلفة البضاعة المباعة</option>
<option value="36"> رواتب وأجور</option>
<option value="37"> عمولات البيع</option>
<option value="38"> الرواتب والرسوم الإدارية</option>
<option value="39"> إيرادات أخرى</option>
<option value="40"> شحن وتخليص جمركي</option>
<option value="41"> تأمين طبي</option>
<option value="42"> مصاريف تسويقية ودعائية</option>
<option value="43"> مصاريف الإيجار</option>
<option value="44"> عمولات وحوافز</option>
<option value="45"> تذاكر سفر</option>
<option value="46"> التأمينات الاجتماعية</option>
<option value="47"> الرسوم الحكومية</option>
<option value="48"> رسوم واشتراكات</option>
<option value="49"> مصاريف مكتبية ومطبوعات</option>
<option value="50"> مصاريف خدمات المكتب</option>
<option value="51"> مصاريف ضيافة</option>
<option value="52"> عمولات بنكية</option>
<option value="53"> مصاريف أخرى</option>
<option value="54"> مصروف إهلاك المباني</option>
<option value="55"> مصروف إهلاك المعدات</option>
<option value="56"> مصروف إهلاك أجهزة مكتبية وطابعات</option>
<option value="57"> مصروف نقل ومواصلات</option>
<option value="58"> الضرائب</option>
<option value="59"> الزكاة</option>
<option value="60"> ترجمة عملات أجنبية</option>
<option value="61"> فوائد</option>
